name: Daily Python Script
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # 每天中午12点运行
 
jobs:
  run-python-script:
   runs-on: windows-latest
   steps:
     - name: Create Executable
       uses: sayyid5416/pyinstaller@v1
       with:
         python_ver: '3.12'
         spec: 'daily_script.py'
