name: Daily Python Script
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # 每天中午12点运行
 
jobs:
  update-txt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 指定您使用的 Python 版本
    - name: Run Python script
      run: python daily_script.py
