name: Daily Python Script
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # 每天中午12点运行
 
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 如果有requirements.txt文件
    - name: Run Python script
      run: python daily_script.py > output.txt
 
    - name: Commit changes
      run: |
        git config --global user.email "474628725@qq.com"
        git config --global user.name "badboy518714"
        git add output.txt
        git commit -m "Update output.txt"
        git push
