name: 更新新疆频道
 
on:
  schedule:
    - cron: 10 2 * * *  # 每天凌晨2点执行
    # - cron: '*/5 * * * *'  # 每分钟执行
  workflow_dispatch:
    
jobs:
  update_txt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git
      env:
        GITHUB TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --global user.email "474628725@qq.com"
        git config --global user.name "smile"
    - name: Update txt file
      run: |
        python XJ_TV.py
        git add xj_tv.m3u
        git commit -m "Update xj_tv.m3u"
        git push
